version: '3.9'

services:
  api:
    build: .
    container_name: sivetel_api
    restart: always
    env_file: .env.production
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - backend

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sivetel
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
    networks:
      - backend

networks:
  backend:
    driver: bridge
