services:
  db:
    image: mysql:8.0
    container_name: sivetel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sivetel
    ports:
      - "3400:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
      
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sivetel_front
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "https://diazysolis.com/phpmyadmin/"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
      
volumes:
  db_data: