version: "3.9"

services:
  api:
    build: .
    container_name: sivetel_api
    restart: always
    env_file: .env.production
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:
    driver: bridge
